@startuml
left to right direction

actor Administrador

rectangle "Sistema de Gestión de Proyectos de Video" {
  Administrador --> (Aprobar Video)
  Administrador --> (Rechazar Video)
  (Aprobar Video) .> (Notificar Usuario) : <<include>>
}
@enduml
