@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "Usuario (Productor/Coordinador)" as user
participant "PantallaProyectos:ui" as ui
participant "ServicioProyectos:ctrl" as ctrl
participant "Validador:val" as val
participant "Proyecto:proy" as proy

user -> ui: abrirEdicion(idProyecto)
activate ui
ui -> ctrl: editarProyecto(idProyecto, cambios)
activate ctrl

ctrl -> val: normalizar(cambios)
activate val
val --> ctrl: datosNormalizados
ctrl -> val: validarDatos(datosNormalizados)
val --> ctrl: resultado(ok, errores)
destroy val

ctrl -> proy: cargar(idProyecto)
activate proy
proy --> ctrl: proyectoActual
ctrl -> proy: aplicarCambios(cambios)
proy --> ctrl: aplicado
ctrl -> proy: guardar()
proy --> ctrl: ok
deactivate proy

ctrl --> ui: okEdicion(idProyecto)
deactivate ctrl
ui -> user: mostrarConfirmacion(idProyecto)
user -> ui: confirmarDetalle(idProyecto)
ui --> user: mostrarDetalle(idProyecto)
deactivate ui
@enduml